language: generic
sudo: required

services:
- docker

script:
- docker run januszmail/test-environment:2 run_tests `if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
