// <auto-generated />
using JanuszMail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JanuszMail.Migrations
{
    [DbContext(typeof(JanuszMailContext))]
    partial class JanuszMailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("JanuszMail.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Provider");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
            modelBuilder.Entity("JanuszMail.Models.ProviderModel", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Login");

                b.Property<string>("Password");

                b.Property<string>("Smtp");

                b.Property<string>("Imap");

                b.Property<int>("UserId");

                b.HasKey("ID");

                b.ToTable("Providers");
            });
#pragma warning restore 612, 618
        }
    }
}
