// <auto-generated />
using JanuszMail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JanuszMail.Migrations.JanuszMailDb
{
    [DbContext(typeof(JanuszMailDbContext))]
    partial class JanuszMailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("JanuszMail.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<int>("ProviderID");

                    b.HasKey("ID");

                    b.HasIndex("ProviderID");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("JanuszMail.Models.ProviderParams", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<int>("ImapPortNumber");

                    b.Property<string>("ImapServerName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("SmtpPortNumber");

                    b.Property<string>("SmtpServerName")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ProviderParams");
                });

            modelBuilder.Entity("JanuszMail.Models.Contact", b =>
                {
                    b.HasOne("JanuszMail.Models.ProviderParams", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
